refactored tests to support evergreen.

diff --git a/.evergreen/.evg.yml b/.evergreen/.evg.yml
--- a/.evergreen/.evg.yml
+++ b/.evergreen/.evg.yml
@@ -1,29 +1,425 @@
+########################################
+# Evergreen Template for MongoDB Drivers
+########################################
+
+# When a task that used to pass starts to fail
+# Go through all versions that may have been skipped to detect
+# when the task started failing
 stepback: true
+
+# Mark a failure as a system/bootstrap failure (purple box) rather then a task
+# failure by default.
+# Actual testing tasks are marked with `type: test`
 command_type: system
+
+# Protect ourself against rogue test case, or curl gone wild, that runs forever
+# 12 minutes is the longest we'll ever run
 exec_timeout_secs: 3600 # 12 minutes is the longest we'll ever run
+
+# What to do when evergreen hits the timeout (`post:` tasks are run automatically)
 timeout:
   - command: shell.exec
     params:
       script: |
         ls -la
 functions:
-  build-all:
+
+  fetch-source:
+    # Executes git clone and applies the submitted patch, if any
+    - command: git.get_project
+      params:
+        directory: src/github.com/10gen/mongo-go-driver         
+    # Deprecated. Should be removed. But still needed for certain agents (ZAP)
+    - command: git.apply_patch
+    # Make an evergreen expansion file with dynamic values
+    - command: shell.exec
+      params:
+        working_dir: src/github.com/10gen/mongo-go-driver
+        script: |
+           if [ "Windows_NT" = "$OS" ]; then
+              export GOPATH=$(cygpath -w $(dirname $(dirname $(dirname $(dirname `pwd`)))))
+           else
+              export GOPATH=$(dirname $(dirname $(dirname $(dirname `pwd`))))
+           fi;
+
+           # Get the current unique version of this checkout
+           if [ "${is_patch}" = "true" ]; then
+              CURRENT_VERSION=$(git describe)-patch-${version_id}
+           else
+              CURRENT_VERSION=latest
+           fi
+
+           export DRIVERS_TOOLS="$(pwd)/../drivers-tools"
+
+           # Python has cygwin path problems on Windows. Detect prospective mongo-orchestration home directory
+           if [ "Windows_NT" == "$OS" ]; then # Magic variable in cygwin
+              export DRIVERS_TOOLS=$(cygpath -m $DRIVERS_TOOLS)
+           fi
+
+           export MONGO_ORCHESTRATION_HOME="$DRIVERS_TOOLS/.evergreen/orchestration"
+           export MONGODB_BINARIES="$DRIVERS_TOOLS/mongodb/bin"
+           export UPLOAD_BUCKET="${project}"
+           export PROJECT_DIRECTORY="$(pwd)"
+           export PATH="${GCC_PATH}:$GOPATH/bin:$MONGODB_BINARIES:$PATH"
+           export PROJECT="${project}"
+
+           cat <<EOT > expansion.yml
+           CURRENT_VERSION: "$CURRENT_VERSION"
+           DRIVERS_TOOLS: "$DRIVERS_TOOLS"
+           MONGO_ORCHESTRATION_HOME: "$MONGO_ORCHESTRATION_HOME"
+           MONGODB_BINARIES: "$MONGODB_BINARIES"
+           UPLOAD_BUCKET: "$UPLOAD_BUCKET"
+           PROJECT_DIRECTORY: "$PROJECT_DIRECTORY"
+           PREPARE_SHELL: |
+              set -o errexit
+              set -o xtrace
+              export GOPATH="$GOPATH"
+              export DRIVERS_TOOLS="$DRIVERS_TOOLS"
+              export MONGO_ORCHESTRATION_HOME="$MONGO_ORCHESTRATION_HOME"
+              export MONGODB_BINARIES="$MONGODB_BINARIES"
+              export UPLOAD_BUCKET="$UPLOAD_BUCKET"
+              export PROJECT_DIRECTORY="$PROJECT_DIRECTORY"
+              export TMPDIR="$MONGO_ORCHESTRATION_HOME/db"
+              export PATH="$PATH"
+              export PROJECT="$PROJECT"
+           EOT
+           # See what we've done
+           cat expansion.yml
+    # Load the expansion file to make an evergreen variable with the current unique version
+    - command: expansions.update
+      params:
+        file: src/github.com/10gen/mongo-go-driver/expansion.yml
+
+
+  prepare-resources:
+    - command: shell.exec
+      params:
+        script: |
+          ${PREPARE_SHELL}
+          rm -rf $DRIVERS_TOOLS
+          if [ "${project}" = "drivers-tools" ]; then
+            # If this was a patch build, doing a fresh clone would not actually test the patch
+            cp -R ${PROJECT_DIRECTORY}/ $DRIVERS_TOOLS
+          else
+            git clone git://github.com/mongodb-labs/drivers-evergreen-tools.git $DRIVERS_TOOLS
+          fi
+          echo "{ \"releases\": { \"default\": \"$MONGODB_BINARIES\" }}" > $MONGO_ORCHESTRATION_HOME/orchestration.config
+    - command: shell.exec
+      params:
+        working_dir: src/github.com/10gen/mongo-go-driver
+        script: |
+           ${PREPARE_SHELL}
+           # any go tools that we need
+           go get -u github.com/golang/lint/golint
+
+           # initialize submodules
+           git submodule init
+           git submodule update
+
+           # generate any source code
+           make generate
+
+
+  upload-mo-artifacts:
+    - command: shell.exec
+      params:
+        script: |
+          ${PREPARE_SHELL}
+          find $MONGO_ORCHESTRATION_HOME -name \*.log | xargs tar czf ${PROJECT_DIRECTORY}/mongodb-logs.tar.gz
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_file: ${PROJECT_DIRECTORY}/mongodb-logs.tar.gz
+        remote_file: ${UPLOAD_BUCKET}/${build_variant}/${revision}/${version_id}/${build_id}/logs/${task_id}-${execution}-mongodb-logs.tar.gz
+        bucket: mciuploads
+        permissions: public-read
+        content_type: ${content_type|application/x-gzip}
+        display_name: "mongodb-logs.tar.gz"
+    - command: s3.put
+      params:
+        aws_key: ${aws_key}
+        aws_secret: ${aws_secret}
+        local_file: ${DRIVERS_TOOLS}/.evergreen/orchestration/server.log
+        remote_file: ${UPLOAD_BUCKET}/${build_variant}/${revision}/${version_id}/${build_id}/logs/${task_id}-${execution}-orchestration.log
+        bucket: mciuploads
+        permissions: public-read
+        content_type: ${content_type|text/plain}
+        display_name: "orchestration.log"
+
+
+  bootstrap-mongo-orchestration:
+    - command: shell.exec
+      params:
+        script: |
+          ${PREPARE_SHELL}
+          MONGODB_VERSION=${VERSION} TOPOLOGY=${TOPOLOGY} AUTH=${AUTH} SSL=${SSL} sh ${DRIVERS_TOOLS}/.evergreen/run-orchestration.sh
+    - command: expansions.update
+      params:
+        file: mo-expansion.yml
+
+
+  cleanup:
+    - command: shell.exec
+      params:
+        script: |
+          ${PREPARE_SHELL}
+          cd "$MONGO_ORCHESTRATION_HOME"
+          # source the mongo-orchestration virtualenv if it exists
+          if [ -f venv/bin/activate ]; then
+            . venv/bin/activate
+          elif [ -f venv/Scripts/activate ]; then
+            . venv/Scripts/activate
+          fi
+          mongo-orchestration stop
+          cd -
+          rm -rf $DRIVERS_TOOLS || true
+
+
+  fix-absolute-paths:
+    - command: shell.exec
+      params:
+        script: |
+          ${PREPARE_SHELL}
+          for filename in $(find ${DRIVERS_TOOLS} -name \*.json); do
+            perl -p -i -e "s|ABSOLUTE_PATH_REPLACEMENT_TOKEN|${DRIVERS_TOOLS}|g" $filename
+          done
+
+
+  windows-fix:
+    - command: shell.exec
+      params:
+        script: |
+          ${PREPARE_SHELL}
+          for i in $(find ${DRIVERS_TOOLS}/.evergreen ${PROJECT_DIRECTORY}/.evergreen -name \*.sh); do
+            cat $i | tr -d '\r' > $i.new
+            mv $i.new $i
+          done
+
+
+  make-files-executable:
+    - command: shell.exec
+      params:
+        script: |
+          ${PREPARE_SHELL}
+          for i in $(find ${DRIVERS_TOOLS}/.evergreen ${PROJECT_DIRECTORY}/.evergreen -name \*.sh); do
+            chmod +x $i
+          done
+
+
+  install-dependencies:
+    type: test
+    params:
+      working_dir: src/github.com/10gen/mongo-go-driver
+      script: |
+        ${PREPARE_SHELL}
+        file="${PROJECT_DIRECTORY}/.evergreen/install-dependencies.sh"
+        [ -f ${file} ] && sh ${file} || echo "${file} not available, skipping"
+  
+
+  run-make:
+    - command: shell.exec
+      params:
+        working_dir: src/github.com/10gen/mongo-go-driver
+        script: |
+          ${PREPARE_SHELL}
+          make ${targets} BUILD_TAGS="-tags gssapi"
+
+
+  run-tests:
     - command: shell.exec
       type: test
       params:
-        working_dir: mongo-csharp-driver
+        working_dir: src/github.com/10gen/mongo-go-driver
         script: |
-          make test-short
-          
+          ${PREPARE_SHELL}
+          AUTH=${AUTH} SSL=${SSL} MONGODB_URI="${MONGODB_URI}" TOPOLOGY=${TOPOLOGY} make evg-test BUILD_TAGS="-tags gssapi"
+
+
+  run-enterprise-auth-tests:
+    - command: shell.exec
+      type: test
+      params:
+        silent: true
+        working_dir: src/github.com/10gen/mongo-go-driver
+        script: |
+          # DO NOT ECHO WITH XTRACE (which PREPARE_SHELL does)
+          if [ "Windows_NT" = "$OS" ]; then
+            export GOPATH=$(cygpath -w $(dirname $(dirname $(dirname $(dirname `pwd`)))))
+          else
+            export GOPATH=$(dirname $(dirname $(dirname $(dirname `pwd`))))
+          fi;
+          export PATH="${GCC_PATH}:$PATH"
+          MONGODB_URI="${MONGODB_URI}" make evg-test-auth BUILD_TAGS="-tags gssapi"
+
+pre:
+  - func: fetch-source
+  - func: prepare-resources
+  - func: windows-fix
+  - func: fix-absolute-paths
+  - func: make-files-executable
+  - func: install-dependencies
+
+post:
+  - command: gotest.parse_files
+    params:
+      files: ["src/github.com/10gen/mongo-go-driver/test.suite"]
+  - func: upload-mo-artifacts
+  - func: cleanup
+
 tasks:
-  - name: build
-    commands:
-      - func: build-all
+    - name: sa-lint
+      tags: ["static-analysis"]
+      commands:
+        - func: run-make
+          vars:
+            targets: lint
+    
+    - name: sa-vet
+      tags: ["static-analysis"]
+      commands:
+        - func: run-make
+          vars:
+            targets: vet
+
+    - name: sa-build-examples
+      tags: ["static-analysis"]
+      commands:
+        - func: run-make
+          vars:
+            targets: build-examples
+
+    - name: test-standalone-noauth-nossl
+      tags: ["test", "standalone"]
+      commands:
+        - func: bootstrap-mongo-orchestration
+        - func: run-tests
+          vars:
+            TOPOLOGY: "server"
+            AUTH: "noauth"
+            SSL: "nossl"
+
+    - name: test-standalone-auth-nossl
+      tags: ["test", "standalone"]
+      commands:
+        - func: bootstrap-mongo-orchestration
+        - func: run-tests
+          vars:
+            TOPOLOGY: "server"
+            AUTH: "auth"
+            SSL: "nossl"
+
+    - name: test-replicaset-noauth-nossl
+      tags: ["test", "replicaset"]
+      commands:
+        - func: bootstrap-mongo-orchestration
+        - func: run-tests
+          vars:
+            TOPOLOGY: "replica_set"
+            AUTH: "noauth"
+            SSL: "nossl"
+
+    - name: test-replicaset-auth-nossl
+      tags: ["test", "replicaset"]
+      commands:
+        - func: bootstrap-mongo-orchestration
+        - func: run-tests
+          vars:
+            TOPOLOGY: "replica_set"
+            AUTH: "auth"
+            SSL: "nossl"
+
+    - name: test-sharded-noauth-nossl
+      tags: ["test", "sharded"]
+      commands:
+        - func: bootstrap-mongo-orchestration
+        - func: run-tests
+          vars:
+            TOPOLOGY: "sharded_cluster"
+            AUTH: "noauth"
+            SSL: "nossl"
+
+    - name: test-sharded-auth-nossl
+      tags: ["test", "sharded"]
+      commands:
+        - func: bootstrap-mongo-orchestration
+        - func: run-tests
+          vars:
+            TOPOLOGY: "sharded_cluster"
+            AUTH: "auth"
+            SSL: "nossl"
+
+    - name: test-enterprise-auth-plain
+      tags: ["test", "enterprise-auth"]
+      commands:
+        - func: run-enterprise-auth-tests
+          vars:
+            MONGODB_URI: "${plain_auth_mongodb_uri}"
+
+    - name: test-enterprise-auth-gssapi
+      tags: ["test", "enterprise-auth"]
+      commands:
+        - func: run-enterprise-auth-tests
+          vars:
+            MONGODB_URI: "${gssapi_auth_mongodb_uri}"
+
+axes:
+  - id: version
+    display_name: MongoDB Version
+    values:
+      - id: "3.4"
+        display_name: "3.4"
+        variables:
+           VERSION: "3.4"
+      - id: "3.2"
+        display_name: "3.2"
+        variables:
+           VERSION: "3.2"
+
+  - id: os
+    display_name: OS
+    values:
+      - id: "windows-64"
+        display_name: "Windows 64-bit"
+        run_on: windows-64-vs2015-small
+        variables:
+          GCC_PATH: "/cygdrive/c/mingw-w64/x86_64-4.9.1-posix-seh-rt_v3-rev1/mingw64/bin"
+      - id: "ubuntu1404-64"
+        display_name: "Ubuntu 14.04"
+        run_on: ubuntu1404-build
+      - id: osx
+        display_name: "OSX 10.10"
+        run_on: osx-1010
+
 
 buildvariants:
-- name: windows-64-compile
-  display_name: "Windows 64-bit compile"
+- name: static-analysis
+  display_name: "Static Analysis"
+  run_on:
+    # we don't care where this one runs
+    - osx-1010
+    - ubuntu1404-build
+  tasks:
+    - name: ".static-analysis"
+
+- name: enterprise-auth-tests-windows
+  display_name: "Enterprise Auth Windows"
   run_on:
     - windows-64-vs2015-small
+  expansions:
+    GCC_PATH: "/cygdrive/c/mingw-w64/x86_64-4.9.1-posix-seh-rt_v3-rev1/mingw64/bin"
   tasks:
-    - name: build
+    - name: ".test .enterprise-auth"
+
+- name: enterprise-auth-tests-linux
+  display_name: "Enterprise Auth Linux"
+  run_on:
+    - ubuntu1404-build
+  tasks:
+    - name: test-enterprise-auth-plain
+
+- matrix_name: "tests"
+  matrix_spec: { version: "*", os: "*" }
+  display_name: "${version} ${os}"
+  tasks:
+     - name: ".test !.enterprise-auth"
