GODRIVER-2411 Allow loading the new csfle dynamic library.

diff --git a/.evergreen/config.yml b/.evergreen/config.yml
--- a/.evergreen/config.yml
+++ b/.evergreen/config.yml
@@ -12,6 +12,9 @@ stepback: true
 # Actual testing tasks are marked with `type: test`
 command_type: setup
 
+# Fail builds when pre tasks fail.
+pre_error_fails_task: true
+
 # Protect ourself against rogue test case, or curl gone wild, that runs forever
 # 12 minutes is the longest we'll ever run
 exec_timeout_secs: 3600 # 12 minutes is the longest we'll ever run
@@ -159,6 +162,32 @@ functions:
           # initialize submodules
           git submodule init
           git submodule update
+    - command: shell.exec
+      params:
+        working_dir: src/go.mongodb.org/mongo-driver
+        script: |
+          ${PREPARE_SHELL}
+
+          # Skip the csfle library download if there is no csfle build for the current platform.
+          # Don't try to determine this automatically to prevent misconfiguration errors from
+          # silently skipping the csfle download and changing the testing conditions.
+          if [ "${SKIP_CSFLE_DOWNLOAD}" = "true" ]; then
+            echo "There is no csfle library for this platform, skipping download..."
+            exit 0
+          fi
+
+          # Download the csfle dynamic library for the current platform to the current working
+          # directory. The run-tests.sh and versioned API test scripts expect to find a
+          # mongo_csfle_v1.* file in the "src/go.mongodb.org/mongo-driver" working directory.
+          # TODO(GODRIVER-2437): Update version to "latest-stable" once the csfle library has a
+          # feature-complete stable release.
+          ${PYTHON3_BINARY} $DRIVERS_TOOLS/.evergreen/mongodl.py \
+            --component csfle \
+            --version latest \
+            --edition enterprise \
+            --out "$(pwd)" \
+            --only "**/mongo_csfle_v1.*" \
+            --strip-path-components 1
 
   install-linters:
     - command: shell.exec
@@ -274,8 +303,8 @@ functions:
             cat $i | tr -d '\r' > $i.new
             mv $i.new $i
           done
-          # Copy client certificate because symlinks do not work on Windows.
-          cp ${DRIVERS_TOOLS}/.evergreen/x509gen/client.pem ${MONGO_ORCHESTRATION_HOME}/lib/client.pem
+          # Copy client certificate because symlinks do not work on Windows. Ignore any copy errors.
+          cp ${DRIVERS_TOOLS}/.evergreen/x509gen/client.pem ${MONGO_ORCHESTRATION_HOME}/lib/client.pem || echo "Ignoring copy error"
 
   make-files-executable:
     - command: shell.exec
@@ -459,6 +488,14 @@ functions:
             export PYTHON="$(pwd)/venv/bin/python"
           fi
           . ${DRIVERS_TOOLS}/.evergreen/csfle/set-temp-creds.sh
+
+          # Find the csfle library file in the current directory and set the CSFLE_PATH to the path of that
+          # file. Only look for .so, .dll, or .dylib files to prevent matching any other downloaded files.
+          export CSFLE_PATH="$(find $(pwd) -maxdepth 1 -type f \
+            -name 'mongo_csfle_v1.so' -o \
+            -name 'mongo_csfle_v1.dll' -o \
+            -name 'mongo_csfle_v1.dylib')"
+          echo "CSFLE_PATH=$CSFLE_PATH"
 
           export GOFLAGS=-mod=vendor
           AUTH="${AUTH}" \
@@ -652,7 +689,9 @@ functions:
     - command: shell.exec
       params:
         script: |
-          DRIVERS_TOOLS=${DRIVERS_TOOLS} MONGODB_URI=${MONGODB_URI} bash ${DRIVERS_TOOLS}/.evergreen/run-load-balancer.sh stop
+          # Attempt to shut down a running load balancer. Ignore any errors that happen if the load
+          # balancer is not running.
+          DRIVERS_TOOLS=${DRIVERS_TOOLS} MONGODB_URI=${MONGODB_URI} bash ${DRIVERS_TOOLS}/.evergreen/run-load-balancer.sh stop || echo "Ignoring load balancer stop error"
 
   add-aws-auth-variables-to-file:
     - command: shell.exec
@@ -1916,6 +1955,9 @@ axes:
           # to prevent attempting to link the client-side encryption (libmongocrypt) binaries when
           # running Go tests.
           GO_BUILD_TAGS: ""
+          # There is no csfle library download for Ubuntu 14.04. Skip downloading it and let the
+          # tests use mongocryptd instead.
+          SKIP_CSFLE_DOWNLOAD: "true"
 
   # OSes that require >= 3.2 for SSL
   - id: os-ssl-32
@@ -1936,6 +1978,9 @@ axes:
         variables:
           GO_DIST: "/opt/golang/go1.17"
           PYTHON3_BINARY: "/opt/python/3.8/bin/python3"
+          # There is no csfle library download for Ubuntu 16.04. Skip downloading it and let the
+          # tests use mongocryptd instead.
+          SKIP_CSFLE_DOWNLOAD: "true"
       - id: "osx-go-1-17"
         display_name: "MacOS 10.14"
         run_on: macos-1014
